/**
 * On-chain delegation proof (KS256 root) — Sig_structure parity with arbor
 * `delegationcert.BuildOnchainDelegationToBeSigned` / the univocity contract's
 * `delegationVerifier.buildSigStructure`. Fixture hex generated from the Go
 * implementation (cbor.Marshal of ["Signature1", protected, h'', payload]).
 */

import { describe, expect, it } from "vitest";
import { keccak_256 } from "@noble/hashes/sha3";
import { secp256k1 } from "@noble/curves/secp256k1";
import {
  buildOnchainDelegationToBeSignedEs256,
  buildOnchainDelegationToBeSignedKs256,
  normalizeEs256SignatureLowS,
  signOnchainDelegationEs256,
  signOnchainDelegationKs256,
  verifyOnchainDelegationSignatureEs256,
  verifyOnchainDelegationSignatureKs256,
} from "../src/index.js";

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const FIXTURE_LOG_ID_HEX = "101112131415161718191a1b1c1d1e1f";
const FIXTURE_MMR_START = 3n;
const FIXTURE_MMR_END = 1n << 40n;
const FIXTURE_X = new Uint8Array(32).map((_, i) => 0xa0 + i);
const FIXTURE_Y = new Uint8Array(32).map((_, i) => 0xc0 + i);

// Generated by arbor delegationcert (Go): KS256 protected header {1: -65799},
// payload = domain ‖ logId32 ‖ mmrStart ‖ mmrEnd ‖ x ‖ y.
const FIXTURE_PROTECTED_HEX = "a1013a00010106";
const FIXTURE_SIGSTRUCTURE_HEX =
  "846a5369676e61747572653147a1013a00010106405891666f726573747269652e756e69766f636974792e64656c65676174696f6e2e763100000000000000000000000000000000101112131415161718191a1b1c1d1e1f00000000000000030000010000000000a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf";

// Anvil dev account 0: address 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266.
const TEST_PRIVATE_KEY_HEX =
  "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const TEST_ADDRESS_HEX = "f39fd6e51aad88f6f4ce6ab8827279cfffb92266";

function fixtureInput() {
  return {
    logIdHex: FIXTURE_LOG_ID_HEX,
    mmrStart: FIXTURE_MMR_START,
    mmrEnd: FIXTURE_MMR_END,
    delegatedKeyX: FIXTURE_X,
    delegatedKeyY: FIXTURE_Y,
  };
}

describe("buildOnchainDelegationToBeSignedKs256", () => {
  it("produces Sig_structure bytes identical to arbor delegationcert (KS256)", () => {
    const tbs = buildOnchainDelegationToBeSignedKs256(fixtureInput());
    expect(bytesToHex(tbs.protectedHeader)).toBe(FIXTURE_PROTECTED_HEX);
    expect(bytesToHex(tbs.sigStructureBytes)).toBe(FIXTURE_SIGSTRUCTURE_HEX);
    expect(bytesToHex(tbs.delegationKey)).toBe(
      bytesToHex(FIXTURE_X) + bytesToHex(FIXTURE_Y),
    );
  });

  it("rejects malformed inputs", () => {
    expect(() =>
      buildOnchainDelegationToBeSignedKs256({
        ...fixtureInput(),
        logIdHex: "abcd",
      }),
    ).toThrow(/log id/i);
    expect(() =>
      buildOnchainDelegationToBeSignedKs256({
        ...fixtureInput(),
        delegatedKeyX: new Uint8Array(31),
      }),
    ).toThrow(/32 bytes/);
  });
});

// Generated by arbor delegationcert (Go): ES256 protected header {1: -7},
// same packed payload as the KS256 fixture.
const FIXTURE_ES256_PROTECTED_HEX = "a10126";
const FIXTURE_ES256_SIGSTRUCTURE_HEX =
  "846a5369676e61747572653143a10126405891666f726573747269652e756e69766f636974792e64656c65676174696f6e2e763100000000000000000000000000000000101112131415161718191a1b1c1d1e1f00000000000000030000010000000000a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf";

async function generateEs256RootKeyPair(): Promise<CryptoKeyPair> {
  return (await crypto.subtle.generateKey(
    { name: "ECDSA", namedCurve: "P-256" },
    true,
    ["sign", "verify"],
  )) as CryptoKeyPair;
}

async function exportEs256Xy(
  publicKey: CryptoKey,
): Promise<{ x: Uint8Array; y: Uint8Array }> {
  const raw = new Uint8Array(await crypto.subtle.exportKey("raw", publicKey));
  return { x: raw.slice(1, 33), y: raw.slice(33, 65) };
}

describe("buildOnchainDelegationToBeSignedEs256", () => {
  it("produces Sig_structure bytes identical to arbor delegationcert (ES256)", () => {
    const tbs = buildOnchainDelegationToBeSignedEs256(fixtureInput());
    expect(bytesToHex(tbs.protectedHeader)).toBe(FIXTURE_ES256_PROTECTED_HEX);
    expect(bytesToHex(tbs.sigStructureBytes)).toBe(
      FIXTURE_ES256_SIGSTRUCTURE_HEX,
    );
    expect(bytesToHex(tbs.delegationKey)).toBe(
      bytesToHex(FIXTURE_X) + bytesToHex(FIXTURE_Y),
    );
  });
});

describe("signOnchainDelegationEs256", () => {
  it("signs SHA-256(Sig_structure) with a 64-byte low-s signature", async () => {
    const rootKeyPair = await generateEs256RootKeyPair();
    const { x, y } = await exportEs256Xy(rootKeyPair.publicKey);
    // ECDSA s is uniform: 16 rounds of accidental low-s is ~2^-16.
    for (let i = 0; i < 16; i++) {
      const proof = await signOnchainDelegationEs256(
        fixtureInput(),
        rootKeyPair,
      );
      expect(proof.signature.length).toBe(64);
      expect(bytesToHex(proof.protectedHeader)).toBe(
        FIXTURE_ES256_PROTECTED_HEX,
      );
      expect(Array.from(proof.signature)).toEqual(
        Array.from(normalizeEs256SignatureLowS(proof.signature)),
      );
      const ok = await verifyOnchainDelegationSignatureEs256(
        fixtureInput(),
        proof.signature,
        x,
        y,
      );
      expect(ok).toBe(true);
    }
  });
});

describe("verifyOnchainDelegationSignatureEs256", () => {
  it("rejects a signature by a different key", async () => {
    const rootKeyPair = await generateEs256RootKeyPair();
    const otherKeyPair = await generateEs256RootKeyPair();
    const { x, y } = await exportEs256Xy(rootKeyPair.publicKey);
    const proof = await signOnchainDelegationEs256(
      fixtureInput(),
      otherKeyPair,
    );
    const ok = await verifyOnchainDelegationSignatureEs256(
      fixtureInput(),
      proof.signature,
      x,
      y,
    );
    expect(ok).toBe(false);
  });

  it("rejects signatures that are not 64 bytes", async () => {
    const rootKeyPair = await generateEs256RootKeyPair();
    const { x, y } = await exportEs256Xy(rootKeyPair.publicKey);
    const ok = await verifyOnchainDelegationSignatureEs256(
      fixtureInput(),
      new Uint8Array(65),
      x,
      y,
    );
    expect(ok).toBe(false);
  });

  it("rejects high-s signatures the contract would reject", async () => {
    // OZ P256.verify rejects s > n/2; WebCrypto accepts both forms. Verify
    // must match the contract so "true" ⇒ on-chain-acceptable bytes.
    const rootKeyPair = await generateEs256RootKeyPair();
    const { x, y } = await exportEs256Xy(rootKeyPair.publicKey);
    const proof = await signOnchainDelegationEs256(fixtureInput(), rootKeyPair);
    const n = BigInt(
      "0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551",
    );
    let s = 0n;
    for (let i = 32; i < 64; i++) {
      s = (s << 8n) | BigInt(proof.signature[i]!);
    }
    // Force the malleable high-s form (n - s). Sign already low-s-normalized.
    const sHigh = n - s;
    const high = new Uint8Array(64);
    high.set(proof.signature.slice(0, 32), 0);
    for (let i = 0; i < 32; i++) {
      high[63 - i] = Number((sHigh >> BigInt(8 * i)) & 0xffn);
    }
    expect(Array.from(normalizeEs256SignatureLowS(high))).toEqual(
      Array.from(proof.signature),
    );
    const okHigh = await verifyOnchainDelegationSignatureEs256(
      fixtureInput(),
      high,
      x,
      y,
    );
    expect(okHigh).toBe(false);
    const okLow = await verifyOnchainDelegationSignatureEs256(
      fixtureInput(),
      proof.signature,
      x,
      y,
    );
    expect(okLow).toBe(true);
  });
});

describe("normalizeEs256SignatureLowS", () => {
  it("maps high-s to n-s and leaves low-s unchanged", async () => {
    // P-256 order n and a known high s = n-1: normalized s must be 1.
    const nHex =
      "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551";
    const n = BigInt("0x" + nHex);
    const r = new Uint8Array(32).fill(1);
    const high = new Uint8Array(64);
    high.set(r, 0);
    const sHigh = n - 1n;
    for (let i = 0; i < 32; i++) {
      high[63 - i] = Number((sHigh >> BigInt(8 * i)) & 0xffn);
    }
    const normalized = normalizeEs256SignatureLowS(high);
    expect(Array.from(normalized.slice(0, 32))).toEqual(Array.from(r));
    expect(bytesToHex(normalized.slice(32))).toBe(
      "0000000000000000000000000000000000000000000000000000000000000001",
    );
    // Already-low-s input is returned byte-identical.
    expect(Array.from(normalizeEs256SignatureLowS(normalized))).toEqual(
      Array.from(normalized),
    );
  });
});

describe("signOnchainDelegationKs256", () => {
  it("signs keccak256(Sig_structure) recoverable to the root address", () => {
    const proof = signOnchainDelegationKs256(
      fixtureInput(),
      TEST_PRIVATE_KEY_HEX,
    );
    expect(proof.signature.length).toBe(65);
    expect(bytesToHex(proof.protectedHeader)).toBe(FIXTURE_PROTECTED_HEX);
    expect(proof.mmrStart).toBe(FIXTURE_MMR_START);
    expect(proof.mmrEnd).toBe(FIXTURE_MMR_END);

    const hash = keccak_256(hexToBytes(FIXTURE_SIGSTRUCTURE_HEX));
    let v = proof.signature[64]!;
    if (v >= 27) v -= 27;
    const sig = secp256k1.Signature.fromCompact(
      proof.signature.slice(0, 64),
    ).addRecoveryBit(v);
    const pub = sig.recoverPublicKey(hash).toRawBytes(false);
    const address = keccak_256(pub.slice(1)).slice(-20);
    expect(bytesToHex(address)).toBe(TEST_ADDRESS_HEX);
  });
});

describe("verifyOnchainDelegationSignatureKs256", () => {
  it("accepts a signature by the expected root EOA", async () => {
    const proof = signOnchainDelegationKs256(
      fixtureInput(),
      TEST_PRIVATE_KEY_HEX,
    );
    const ok = await verifyOnchainDelegationSignatureKs256(
      fixtureInput(),
      proof.signature,
      hexToBytes(TEST_ADDRESS_HEX),
    );
    expect(ok).toBe(true);
  });

  it("rejects a signature by a different key", async () => {
    const otherKey =
      "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";
    const proof = signOnchainDelegationKs256(fixtureInput(), otherKey);
    const ok = await verifyOnchainDelegationSignatureKs256(
      fixtureInput(),
      proof.signature,
      hexToBytes(TEST_ADDRESS_HEX),
    );
    expect(ok).toBe(false);
  });

  it("rejects recovery ids outside {0, 1} (contract parity)", async () => {
    // Contract does `v < 27 → v += 27` then ecrecover; recovery ids 2/3
    // cannot succeed on-chain. Reachable only when r ≥ n (≈2⁻¹²⁸).
    const proof = signOnchainDelegationKs256(
      fixtureInput(),
      TEST_PRIVATE_KEY_HEX,
    );
    const mutated = new Uint8Array(proof.signature);
    mutated[64] = 2;
    const ok = await verifyOnchainDelegationSignatureKs256(
      fixtureInput(),
      mutated,
      hexToBytes(TEST_ADDRESS_HEX),
    );
    expect(ok).toBe(false);
  });
});

describe("exported on-chain vectors (FOR-332)", () => {
  it("KS256 vector signature verifies against the fixture root", async () => {
    // Pins testdata/onchain-delegation-vectors.json to the live signer so a
    // stale checked-in copy fails here before the univocity forge consumer.
    const { readFileSync } = await import("node:fs");
    const { fileURLToPath } = await import("node:url");
    const { dirname, join } = await import("node:path");
    const root = join(dirname(fileURLToPath(import.meta.url)), "..");
    const vectors = JSON.parse(
      readFileSync(
        join(root, "testdata/onchain-delegation-vectors.json"),
        "utf8",
      ),
    ) as {
      ks256: {
        signature: string;
        rootAddress: string;
        logIdHex: string;
        mmrStart: string;
        mmrEnd: string;
        delegatedKeyX: string;
        delegatedKeyY: string;
      };
    };
    const v = vectors.ks256;
    const ok = await verifyOnchainDelegationSignatureKs256(
      {
        logIdHex: v.logIdHex,
        mmrStart: BigInt(v.mmrStart),
        mmrEnd: BigInt(v.mmrEnd),
        delegatedKeyX: hexToBytes(v.delegatedKeyX),
        delegatedKeyY: hexToBytes(v.delegatedKeyY),
      },
      hexToBytes(v.signature),
      hexToBytes(v.rootAddress),
    );
    expect(ok).toBe(true);
  });

  it("ES256 vector signature verifies against the fixture root", async () => {
    const { readFileSync } = await import("node:fs");
    const { fileURLToPath } = await import("node:url");
    const { dirname, join } = await import("node:path");
    const root = join(dirname(fileURLToPath(import.meta.url)), "..");
    const vectors = JSON.parse(
      readFileSync(
        join(root, "testdata/onchain-delegation-vectors.json"),
        "utf8",
      ),
    ) as {
      es256: {
        signature: string;
        rootX: string;
        rootY: string;
        logIdHex: string;
        mmrStart: string;
        mmrEnd: string;
        delegatedKeyX: string;
        delegatedKeyY: string;
      };
    };
    const v = vectors.es256;
    const ok = await verifyOnchainDelegationSignatureEs256(
      {
        logIdHex: v.logIdHex,
        mmrStart: BigInt(v.mmrStart),
        mmrEnd: BigInt(v.mmrEnd),
        delegatedKeyX: hexToBytes(v.delegatedKeyX),
        delegatedKeyY: hexToBytes(v.delegatedKeyY),
      },
      hexToBytes(v.signature),
      hexToBytes(v.rootX),
      hexToBytes(v.rootY),
    );
    expect(ok).toBe(true);
  });
});
