/**
 * On-chain delegation proof (KS256 root) — Sig_structure parity with arbor
 * `delegationcert.BuildOnchainDelegationToBeSigned` / the univocity contract's
 * `delegationVerifier.buildSigStructure`. Fixture hex generated from the Go
 * implementation (cbor.Marshal of ["Signature1", protected, h'', payload]).
 */

import { describe, expect, it } from "vitest";
import { keccak_256 } from "@noble/hashes/sha3";
import { secp256k1 } from "@noble/curves/secp256k1";
import {
  buildOnchainDelegationToBeSigned,
  signOnchainDelegationKs256,
  verifyOnchainDelegationSignatureKs256,
} from "../src/index.js";

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const FIXTURE_LOG_ID_HEX = "101112131415161718191a1b1c1d1e1f";
const FIXTURE_MMR_START = 3n;
const FIXTURE_MMR_END = 1n << 40n;
const FIXTURE_X = new Uint8Array(32).map((_, i) => 0xa0 + i);
const FIXTURE_Y = new Uint8Array(32).map((_, i) => 0xc0 + i);

// Generated by arbor delegationcert (Go): KS256 protected header {1: -65799},
// payload = domain ‖ logId32 ‖ mmrStart ‖ mmrEnd ‖ x ‖ y.
const FIXTURE_PROTECTED_HEX = "a1013a00010106";
const FIXTURE_SIGSTRUCTURE_HEX =
  "846a5369676e61747572653147a1013a00010106405891666f726573747269652e756e69766f636974792e64656c65676174696f6e2e763100000000000000000000000000000000101112131415161718191a1b1c1d1e1f00000000000000030000010000000000a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf";

// Anvil dev account 0: address 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266.
const TEST_PRIVATE_KEY_HEX =
  "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const TEST_ADDRESS_HEX = "f39fd6e51aad88f6f4ce6ab8827279cfffb92266";

function fixtureInput() {
  return {
    logIdHex: FIXTURE_LOG_ID_HEX,
    mmrStart: FIXTURE_MMR_START,
    mmrEnd: FIXTURE_MMR_END,
    delegatedKeyX: FIXTURE_X,
    delegatedKeyY: FIXTURE_Y,
  };
}

describe("buildOnchainDelegationToBeSigned", () => {
  it("produces Sig_structure bytes identical to arbor delegationcert (KS256)", () => {
    const tbs = buildOnchainDelegationToBeSigned(fixtureInput());
    expect(bytesToHex(tbs.protectedHeader)).toBe(FIXTURE_PROTECTED_HEX);
    expect(bytesToHex(tbs.sigStructureBytes)).toBe(FIXTURE_SIGSTRUCTURE_HEX);
    expect(bytesToHex(tbs.delegationKey)).toBe(
      bytesToHex(FIXTURE_X) + bytesToHex(FIXTURE_Y),
    );
  });

  it("rejects malformed inputs", () => {
    expect(() =>
      buildOnchainDelegationToBeSigned({
        ...fixtureInput(),
        logIdHex: "abcd",
      }),
    ).toThrow(/log id/i);
    expect(() =>
      buildOnchainDelegationToBeSigned({
        ...fixtureInput(),
        delegatedKeyX: new Uint8Array(31),
      }),
    ).toThrow(/32 bytes/);
  });
});

describe("signOnchainDelegationKs256", () => {
  it("signs keccak256(Sig_structure) recoverable to the root address", () => {
    const proof = signOnchainDelegationKs256(
      fixtureInput(),
      TEST_PRIVATE_KEY_HEX,
    );
    expect(proof.signature.length).toBe(65);
    expect(bytesToHex(proof.protectedHeader)).toBe(FIXTURE_PROTECTED_HEX);
    expect(proof.mmrStart).toBe(FIXTURE_MMR_START);
    expect(proof.mmrEnd).toBe(FIXTURE_MMR_END);

    const hash = keccak_256(hexToBytes(FIXTURE_SIGSTRUCTURE_HEX));
    let v = proof.signature[64]!;
    if (v >= 27) v -= 27;
    const sig = secp256k1.Signature.fromCompact(
      proof.signature.slice(0, 64),
    ).addRecoveryBit(v);
    const pub = sig.recoverPublicKey(hash).toRawBytes(false);
    const address = keccak_256(pub.slice(1)).slice(-20);
    expect(bytesToHex(address)).toBe(TEST_ADDRESS_HEX);
  });
});

describe("verifyOnchainDelegationSignatureKs256", () => {
  it("accepts a signature by the expected root EOA", async () => {
    const proof = signOnchainDelegationKs256(
      fixtureInput(),
      TEST_PRIVATE_KEY_HEX,
    );
    const ok = await verifyOnchainDelegationSignatureKs256(
      fixtureInput(),
      proof.signature,
      hexToBytes(TEST_ADDRESS_HEX),
    );
    expect(ok).toBe(true);
  });

  it("rejects a signature by a different key", async () => {
    const otherKey =
      "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";
    const proof = signOnchainDelegationKs256(fixtureInput(), otherKey);
    const ok = await verifyOnchainDelegationSignatureKs256(
      fixtureInput(),
      proof.signature,
      hexToBytes(TEST_ADDRESS_HEX),
    );
    expect(ok).toBe(false);
  });
});
