version: '3'

vars:
  CANOPY_DIR: './packages/apps/canopy'
  CANOPY_ID: '{{.CANOPY_ID}}'
  FOREST_PROJECT_ID: '{{.FOREST_PROJECT_ID}}'

tasks:
  all:
    desc: Build all packages in the monorepo
    cmds:
      - echo "🔨 Building all packages..."
      - pnpm run build
      - echo "✅ Build complete!"

  canopy:
    desc: Build SvelteKit app for Cloudflare Workers
    dir: '{{.CANOPY_DIR}}'
    cmds:
      - echo "🏗️  Building Canopy app for Cloudflare Workers..."
      - pnpm run build
      - echo "✅ Canopy build complete!"

  shared:
    desc: Build shared packages (cbor, scitt, mmr utils)
    cmds:
      - echo "📦 Building shared packages..."
      - pnpm --filter "./packages/shared/*" run build
      - echo "✅ Shared packages built!"

  clean:
    desc: Clean all build artifacts
    cmds:
      - echo "🧹 Cleaning build artifacts..."
      - rm -rf packages/apps/canopy/.svelte-kit
      - rm -rf packages/apps/canopy/build
      - rm -rf packages/shared/*/dist
      - rm -rf packages/shared/*/build
      - echo "✅ Clean complete!"

  watch:
    desc: Build and watch for changes
    cmds:
      - echo "👀 Starting build watch mode..."
      - pnpm run build --watch

  check:
    desc: Type-check all TypeScript code
    cmds:
      - echo "🔍 Type-checking TypeScript..."
      - pnpm -r run check
      - echo "✅ Type check complete!"

  lint:
    desc: Lint and format check all code
    cmds:
      - echo "🎨 Linting code..."
      - pnpm run lint
      - pnpm run check
      - echo "✅ Linting complete!"

  preview:
    desc: Preview production build locally
    dir: '{{.CANOPY_DIR}}'
    deps: [canopy]
    cmds:
      - echo "🚀 Starting preview server..."
      - pnpm run preview

  vercel:
    desc: Simulate Vercel build process locally
    dir: '{{.CANOPY_DIR}}'
    env:
      VERCEL: '1'
      VERCEL_ENV: 'production'
      CANOPY_ID: '{{.CANOPY_ID}}'
      FOREST_PROJECT_ID: '{{.FOREST_PROJECT_ID}}'
    cmds:
      - echo "🔺 Building with Vercel configuration..."
      - 'echo "  CANOPY_ID: {{.CANOPY_ID}}"'
      - 'echo "  FOREST_PROJECT_ID: {{.FOREST_PROJECT_ID}}"'
      - pnpm run build
      - echo "✅ Vercel build simulation complete!"