export const FOREST_GENESIS_LABEL_GENESIS_VERSION = -68009;
export const FOREST_GENESIS_LABEL_GENESIS_ALG = -68014;
export const FOREST_GENESIS_LABEL_BOOTSTRAP_KEY = -68015;
export const FOREST_GENESIS_LABEL_UNIVOCITY_ADDR = -68011;
export const FOREST_GENESIS_LABEL_CHAIN_ID = -68013;
export const FOREST_GENESIS_SCHEMA_V2 = 2;
export const FOREST_GENESIS_SCHEMA_V1 = 1;

export const HEADER_IDTIMESTAMP = -65537;
export const HEADER_FORESTRIE_GRANT_V0 = -65538;
