name = "canopy"
main = "./.svelte-kit/cloudflare/index.js"
compatibility_date = "2024-10-01"

[vars]
CANOPY_ID = "canopy-dev-1"
FOREST_PROJECT_ID = "forest-dev-1"
API_VERSION = "v1"
NODE_ENV = "development"
R2_WRITER = "${R2_WRITER}"

# R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "canopy-dev-1-statements"

# Development server configuration
[dev]
port = 8788
local_protocol = "http"

# Build configuration
[build]
command = "pnpm build"

# Environment specific configuration can be added
[env.production]
vars = { NODE_ENV = "production" }

[env.staging]
vars = { NODE_ENV = "staging" }